### ISSUE TITLE
allow out-of-line tags/links in `transaction`

### ISSUE THREAD

**Issue by maxheld83** [SEIAROTg/autobean-refactor#2]
as per the docs, this is not currently supported:

> Full beancount v2 syntax support (except out-of-line tags / links in transaction).

Just logging this here for the sake of completeness.

I stumbled upon this and was (initially) a bit confused by the thrown exception:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/lark/lexer.py", line 665, in lex
    yield lexer.next_token(lexer_state, parser_state)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lark/lexer.py", line 598, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '^' in the current parser context, at line 34 col 3

  ^useR2019
  ^
Expected one of: 
        * POSTING_FLAG
        * INLINE_COMMENT
        * BLOCK_COMMENT
        * INDENT
        * NEVER2
        * _NEWLINE
        * WHITESPACE
        * NEVER
        * _NEWLINE_INDENT_COMMENT
        * META_KEY
        * ACCOUNT

Previous tokens: Token('_NEWLINE_INDENT_COMMENT', '\n  ')
```

(awesome work, again 🙏)

**Comment by SEIAROTg** [comment]
Transferring to upstream library.

Context: it's complex with many hard decisions to make and I don't have good answers yet, e.g.

- How do we design the full API to express complex operations?
  - Get tags at line X index Y.
  - Add tags to a new line.
  - Delete whole line of tags.
  - Access comments.
      - Which object to attach comments? The last tag / link? The line? Which line?
- What's the reasonable default in simplified API?
  - If it's `#foo\n^bar\n#baz` and the user inserts a tag between `#foo` and `#baz`, which line should it go to?
  - If it's `#foo #bar ;comment\n#baz` and the user deletes range [#bar..#baz], where should the comment go?
  - If all tags / links in a line is deleted, where should the inline comment go?
